[project]
name = "locomo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.13.0",
    "anthropic>=0.103.1",
    "bert-score>=0.3.13",
    "google-generativeai>=0.8.6",
    "huggingface-hub>=1.16.0",
    "icrawler>=0.6.10",
    "matplotlib>=3.10.9",
    "nltk>=3.9.4",
    "numpy>=2.4.6",
    "openai>=2.37.0",
    "opencv-python>=4.13.0.92",
    "pandas>=3.0.3",
    "peft>=0.19.1",
    "pillow>=12.2.0",
    "pycocoevalcap>=1.2",
    "pydantic>=2.13.4",
    "regex>=2026.5.9",
    "requests>=2.34.2",
    "rouge>=1.0.1",
    "safetensors>=0.7.0",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
    "seaborn>=0.13.2",
    "sentence-transformers>=5.5.1",
    "spacy>=3.8.14",
    "tiktoken>=0.13.0",
    "timm>=1.0.27",
    "tqdm>=4.67.3",
    "transformers>=5.9.0",
    "webdataset>=1.0.2",
]
